const { chromium } = require('playwright')

async function main() {
  const browser = await chromium.launch({
    headless: true,
    args: ['--disable-blink-features=AutomationControlled', '--disable-dev-shm-usage', '--no-sandbox', '--disable-setuid-sandbox']
  })
  const context = await browser.newContext({
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
    viewport: { width: 1280, height: 720 },
  })
  const page = await context.newPage()
  await page.addInitScript(() => { Object.defineProperty(navigator, 'webdriver', { get: () => undefined }) })
  page.setDefaultTimeout(15000)
  try {
    console.log('STEP_START:1:Navigate to login page')
    await page.goto('https://practice.qabrains.com/ecommerce/login')
    await page.waitForLoadState('load')
    await page.screenshot({ path: 'screenshots/step_1.png' })
    console.log('STEP_END:1:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:2:Enter email and password')
    const emailInput = page.getByLabel('Email')
    await emailInput.waitFor({ state: 'visible', timeout: 10000 })
    await emailInput.fill('test@qabrains.com')
    const passwordInput = page.getByLabel('Password')
    await passwordInput.waitFor({ state: 'visible', timeout: 10000 })
    await passwordInput.fill('Password123')
    await page.screenshot({ path: 'screenshots/step_2.png' })
    console.log('STEP_END:2:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:3:Click the Login button')
    const loginBtn = page.getByRole('button', { name: /login/i })
    await loginBtn.waitFor({ state: 'visible', timeout: 10000 })
    await loginBtn.click()
    await page.waitForLoadState('load')
    await page.screenshot({ path: 'screenshots/step_3.png' })
    console.log('STEP_END:3:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:4:Verify navigation to homepage')
    await page.waitForURL('https://practice.qabrains.com/ecommerce', { timeout: 10000 })
    const productsText = page.getByText(/products/i)
    await productsText.waitFor({ state: 'visible', timeout: 10000 })
    await page.screenshot({ path: 'screenshots/step_4.png' })
    console.log('STEP_END:4:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:5:Add item to cart')
    const addToCartBtn = page.getByRole('button', { name: /add to cart/i }).first()
    await addToCartBtn.waitFor({ state: 'visible', timeout: 10000 })
    await addToCartBtn.click()
    await page.screenshot({ path: 'screenshots/step_5.png' })
    console.log('STEP_END:5:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:6:Click the cart icon')
    const cartIcon = page.locator('svg[viewBox="0 0 576 512"]')
    await cartIcon.waitFor({ state: 'visible', timeout: 10000 })
    await cartIcon.click()
    await page.waitForLoadState('load')
    await page.screenshot({ path: 'screenshots/step_6.png' })
    console.log('STEP_END:6:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:7:Verify navigation to cart page')
    await page.waitForURL('https://practice.qabrains.com/ecommerce/cart', { timeout: 10000 })
    await page.screenshot({ path: 'screenshots/step_7.png' })
    console.log('STEP_END:7:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:8:Click the Checkout button')
    const checkoutBtn = page.getByRole('button', { name: /checkout/i })
    await checkoutBtn.waitFor({ state: 'visible', timeout: 10000 })
    await checkoutBtn.click()
    await page.waitForLoadState('load')
    await page.screenshot({ path: 'screenshots/step_8.png' })
    console.log('STEP_END:8:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:9:Verify navigation to checkout info page')
    await page.waitForURL('https://practice.qabrains.com/ecommerce/checkout-info', { timeout: 10000 })
    await page.screenshot({ path: 'screenshots/step_9.png' })
    console.log('STEP_END:9:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:10:Enter First Name and Last Name')
    const firstNameInput = page.getByPlaceholder('Ex. John')
    await firstNameInput.waitFor({ state: 'visible', timeout: 10000 })
    await firstNameInput.fill('John')
    const lastNameInput = page.getByPlaceholder('Ex. Doe')
    await lastNameInput.waitFor({ state: 'visible', timeout: 10000 })
    await lastNameInput.fill('Doe')
    await page.screenshot({ path: 'screenshots/step_10.png' })
    console.log('STEP_END:10:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:11:Click the Continue button')
    const continueBtn = page.getByRole('button', { name: /continue/i })
    await continueBtn.waitFor({ state: 'visible', timeout: 10000 })
    await continueBtn.click()
    await page.waitForLoadState('load')
    await page.screenshot({ path: 'screenshots/step_11.png' })
    console.log('STEP_END:11:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:12:Verify navigation to checkout overview page')
    await page.waitForURL('https://practice.qabrains.com/ecommerce/checkout-overview', { timeout: 10000 })
    await page.screenshot({ path: 'screenshots/step_12.png' })
    console.log('STEP_END:12:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:13:Click the Finish button')
    const finishBtn = page.getByRole('button', { name: /finish/i })
    await finishBtn.waitFor({ state: 'visible', timeout: 10000 })
    await finishBtn.click()
    await page.waitForLoadState('load')
    await page.screenshot({ path: 'screenshots/step_13.png' })
    console.log('STEP_END:13:passed')
    await page.waitForTimeout(1000)

    console.log('STEP_START:14:Verify navigation to checkout complete page')
    await page.waitForURL('https://practice.qabrains.com/ecommerce/checkout-complete', { timeout: 10000 })
    const checkoutCompleteText = page.getByText(/checkout: complete!/i)
    await checkoutCompleteText.waitFor({ state: 'visible', timeout: 10000 })
    await page.screenshot({ path: 'screenshots/step_14.png' })
    console.log('STEP_END:14:passed')
    await page.waitForTimeout(1000)

  } catch (e) {
    console.error(e.message)
    process.exit(1)
  } finally {
    await context.close()
    await browser.close()
  }
}
main()